version: '3.1'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chat-claude
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "52000:3306"

volumes:
  db_data: